// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwwayxznqosseilnafnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13d2F5eHpucW9zc2VpbG5hZm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTc1MDIsImV4cCI6MjA2NTM3MzUwMn0.bGBMxkXt-yU1JOdj9hpUvXXjxgRJ3YbnGPUgqLcGoe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);